name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build and Store Python Package"]
    types:
      - completed
jobs:
  publish-to-pypi:
    name: "Publish Python 🐍 distribution 📦 to PyPI"
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: pybuild
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
